; platformio.ini
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_speed = 921600
; upload_port = /dev/ttyUSB0
upload_port = /dev/ttyACM0

build_type = release
build_unflags = -Og -g -ggdb  
build_flags =
    -O3
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Wl,--relax  

monitor_speed = 115200
monitor_filters = printable, send_on_enter, time
