; platformio.ini
[env:esp32-c3-super-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

upload_speed = 921600
upload_port = /dev/ttyACM0

build_type = release
build_unflags = -Og -g -ggdb  
build_flags =
    -O3
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Wl,--relax  

lib_deps =
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0

monitor_speed = 115200
monitor_filters = printable, send_on_enter, time

